# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/whorlmap-paper',
                'doc_host': 'https://sangyu.github.io',
                'git_url': 'https://github.com/sangyu/whorlmap-paper',
                'lib_path': 'whorlmap_paper'},
  'syms': {'whorlmap_paper.core': {'whorlmap_paper.core.foo': ('core.html#foo', 'whorlmap_paper/core.py')}}}
